# Generated by Django 5.1.3 on 2024-11-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testLiderazgo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='prepa_procedencia',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
